$kind: http-request
name: GET Settings
method: GET
url: '{{baseUrl}}/settings'
order: 1000
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      pm.test("Status is 200", function() {
        pm.response.to.have.status(200);
      });
      pm.test("Response has status true", function() {
        const json = pm.response.json();
        pm.expect(json.status).to.be.true;
      });
